//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QLTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public decimal ID { get; set; }
        public decimal ID_USER { get; set; }
        public System.DateTime TIME { get; set; }
        public string ACTION { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
