//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QLTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_BAO_CAO_LICH_SU_GD
    {
        public Nullable<System.DateTime> Ngày_giao_dịch { get; set; }
        public string Tên_giao_dịch { get; set; }
        public string Danh_mục_thu_chi { get; set; }
        public string Loại_giao_dịch { get; set; }
        public Nullable<decimal> Số_tiền { get; set; }
        public string Đơn_vị_tính { get; set; }
        public string Quỹ_giao_dịch { get; set; }
        public string Ghi_chú { get; set; }
        public decimal STT { get; set; }
    }
}
