//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QLTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.DM_QUY = new HashSet<DM_QUY>();
            this.DM_THU_CHI = new HashSet<DM_THU_CHI>();
            this.LOGs = new HashSet<LOG>();
        }
    
        public decimal ID { get; set; }
        public string USER_NAME { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string FACEBOOK { get; set; }
        public string GHI_CHU { get; set; }
        public string ROLE { get; set; }
    
        public virtual ICollection<DM_QUY> DM_QUY { get; set; }
        public virtual ICollection<DM_THU_CHI> DM_THU_CHI { get; set; }
        public virtual ICollection<LOG> LOGs { get; set; }
    }
}
