//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QLTC_MVCModel", "FK_DM_QUY_DM_DVT", "DM_DVT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcQLTC.Models.DM_DVT), "DM_QUY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcQLTC.Models.DM_QUY), true)]
[assembly: EdmRelationshipAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_DVT", "DM_DVT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcQLTC.Models.DM_DVT), "GD_THU_CHI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcQLTC.Models.GD_THU_CHI), true)]
[assembly: EdmRelationshipAttribute("QLTC_MVCModel", "FK_DM_QUY_USER", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcQLTC.Models.USER), "DM_QUY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcQLTC.Models.DM_QUY), true)]
[assembly: EdmRelationshipAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_QUY", "DM_QUY", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcQLTC.Models.DM_QUY), "GD_THU_CHI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcQLTC.Models.GD_THU_CHI), true)]
[assembly: EdmRelationshipAttribute("QLTC_MVCModel", "FK_DM_THU_CHI_DM_TU_DIEN", "DM_TU_DIEN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcQLTC.Models.DM_TU_DIEN), "DM_THU_CHI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcQLTC.Models.DM_THU_CHI), true)]
[assembly: EdmRelationshipAttribute("QLTC_MVCModel", "FK_DM_THU_CHI_USER", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcQLTC.Models.USER), "DM_THU_CHI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcQLTC.Models.DM_THU_CHI), true)]
[assembly: EdmRelationshipAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_THU_CHI", "DM_THU_CHI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcQLTC.Models.DM_THU_CHI), "GD_THU_CHI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcQLTC.Models.GD_THU_CHI), true)]
[assembly: EdmRelationshipAttribute("QLTC_MVCModel", "FK_LOG_USER", "USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcQLTC.Models.USER), "LOG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcQLTC.Models.LOG), true)]

#endregion

namespace MvcQLTC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QLTC_MVCEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QLTC_MVCEntities object using the connection string found in the 'QLTC_MVCEntities' section of the application configuration file.
        /// </summary>
        public QLTC_MVCEntities() : base("name=QLTC_MVCEntities", "QLTC_MVCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLTC_MVCEntities object.
        /// </summary>
        public QLTC_MVCEntities(string connectionString) : base(connectionString, "QLTC_MVCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QLTC_MVCEntities object.
        /// </summary>
        public QLTC_MVCEntities(EntityConnection connection) : base(connection, "QLTC_MVCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DM_DVT> DM_DVT
        {
            get
            {
                if ((_DM_DVT == null))
                {
                    _DM_DVT = base.CreateObjectSet<DM_DVT>("DM_DVT");
                }
                return _DM_DVT;
            }
        }
        private ObjectSet<DM_DVT> _DM_DVT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DM_QUY> DM_QUY
        {
            get
            {
                if ((_DM_QUY == null))
                {
                    _DM_QUY = base.CreateObjectSet<DM_QUY>("DM_QUY");
                }
                return _DM_QUY;
            }
        }
        private ObjectSet<DM_QUY> _DM_QUY;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DM_THU_CHI> DM_THU_CHI
        {
            get
            {
                if ((_DM_THU_CHI == null))
                {
                    _DM_THU_CHI = base.CreateObjectSet<DM_THU_CHI>("DM_THU_CHI");
                }
                return _DM_THU_CHI;
            }
        }
        private ObjectSet<DM_THU_CHI> _DM_THU_CHI;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DM_TU_DIEN> DM_TU_DIEN
        {
            get
            {
                if ((_DM_TU_DIEN == null))
                {
                    _DM_TU_DIEN = base.CreateObjectSet<DM_TU_DIEN>("DM_TU_DIEN");
                }
                return _DM_TU_DIEN;
            }
        }
        private ObjectSet<DM_TU_DIEN> _DM_TU_DIEN;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GD_THU_CHI> GD_THU_CHI
        {
            get
            {
                if ((_GD_THU_CHI == null))
                {
                    _GD_THU_CHI = base.CreateObjectSet<GD_THU_CHI>("GD_THU_CHI");
                }
                return _GD_THU_CHI;
            }
        }
        private ObjectSet<GD_THU_CHI> _GD_THU_CHI;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LOG> LOGs
        {
            get
            {
                if ((_LOGs == null))
                {
                    _LOGs = base.CreateObjectSet<LOG>("LOGs");
                }
                return _LOGs;
            }
        }
        private ObjectSet<LOG> _LOGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USER> USERs
        {
            get
            {
                if ((_USERs == null))
                {
                    _USERs = base.CreateObjectSet<USER>("USERs");
                }
                return _USERs;
            }
        }
        private ObjectSet<USER> _USERs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DM_DVT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDM_DVT(DM_DVT dM_DVT)
        {
            base.AddObject("DM_DVT", dM_DVT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DM_QUY EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDM_QUY(DM_QUY dM_QUY)
        {
            base.AddObject("DM_QUY", dM_QUY);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DM_THU_CHI EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDM_THU_CHI(DM_THU_CHI dM_THU_CHI)
        {
            base.AddObject("DM_THU_CHI", dM_THU_CHI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DM_TU_DIEN EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDM_TU_DIEN(DM_TU_DIEN dM_TU_DIEN)
        {
            base.AddObject("DM_TU_DIEN", dM_TU_DIEN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GD_THU_CHI EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGD_THU_CHI(GD_THU_CHI gD_THU_CHI)
        {
            base.AddObject("GD_THU_CHI", gD_THU_CHI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LOGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLOGs(LOG lOG)
        {
            base.AddObject("LOGs", lOG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSERs(USER uSER)
        {
            base.AddObject("USERs", uSER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTC_MVCModel", Name="DM_DVT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DM_DVT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DM_DVT object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tEN">Initial value of the TEN property.</param>
        /// <param name="kI_HIEU">Initial value of the KI_HIEU property.</param>
        /// <param name="qUY_DOI_USD">Initial value of the QUY_DOI_USD property.</param>
        public static DM_DVT CreateDM_DVT(global::System.Decimal id, global::System.String tEN, global::System.String kI_HIEU, global::System.Decimal qUY_DOI_USD)
        {
            DM_DVT dM_DVT = new DM_DVT();
            dM_DVT.ID = id;
            dM_DVT.TEN = tEN;
            dM_DVT.KI_HIEU = kI_HIEU;
            dM_DVT.QUY_DOI_USD = qUY_DOI_USD;
            return dM_DVT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TEN
        {
            get
            {
                return _TEN;
            }
            set
            {
                OnTENChanging(value);
                ReportPropertyChanging("TEN");
                _TEN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TEN");
                OnTENChanged();
            }
        }
        private global::System.String _TEN;
        partial void OnTENChanging(global::System.String value);
        partial void OnTENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KI_HIEU
        {
            get
            {
                return _KI_HIEU;
            }
            set
            {
                OnKI_HIEUChanging(value);
                ReportPropertyChanging("KI_HIEU");
                _KI_HIEU = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("KI_HIEU");
                OnKI_HIEUChanged();
            }
        }
        private global::System.String _KI_HIEU;
        partial void OnKI_HIEUChanging(global::System.String value);
        partial void OnKI_HIEUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal QUY_DOI_USD
        {
            get
            {
                return _QUY_DOI_USD;
            }
            set
            {
                OnQUY_DOI_USDChanging(value);
                ReportPropertyChanging("QUY_DOI_USD");
                _QUY_DOI_USD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QUY_DOI_USD");
                OnQUY_DOI_USDChanged();
            }
        }
        private global::System.Decimal _QUY_DOI_USD;
        partial void OnQUY_DOI_USDChanging(global::System.Decimal value);
        partial void OnQUY_DOI_USDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHI_CHU
        {
            get
            {
                return _GHI_CHU;
            }
            set
            {
                OnGHI_CHUChanging(value);
                ReportPropertyChanging("GHI_CHU");
                _GHI_CHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHI_CHU");
                OnGHI_CHUChanged();
            }
        }
        private global::System.String _GHI_CHU;
        partial void OnGHI_CHUChanging(global::System.String value);
        partial void OnGHI_CHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_DM_QUY_DM_DVT", "DM_QUY")]
        public EntityCollection<DM_QUY> DM_QUY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DM_QUY>("QLTC_MVCModel.FK_DM_QUY_DM_DVT", "DM_QUY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DM_QUY>("QLTC_MVCModel.FK_DM_QUY_DM_DVT", "DM_QUY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_DVT", "GD_THU_CHI")]
        public EntityCollection<GD_THU_CHI> GD_THU_CHI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_DVT", "GD_THU_CHI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_DVT", "GD_THU_CHI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTC_MVCModel", Name="DM_QUY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DM_QUY : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DM_QUY object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iD_USER">Initial value of the ID_USER property.</param>
        /// <param name="tEN">Initial value of the TEN property.</param>
        /// <param name="sO_TIEN">Initial value of the SO_TIEN property.</param>
        /// <param name="iD_DVT">Initial value of the ID_DVT property.</param>
        public static DM_QUY CreateDM_QUY(global::System.Decimal id, global::System.Decimal iD_USER, global::System.String tEN, global::System.Decimal sO_TIEN, global::System.Decimal iD_DVT)
        {
            DM_QUY dM_QUY = new DM_QUY();
            dM_QUY.ID = id;
            dM_QUY.ID_USER = iD_USER;
            dM_QUY.TEN = tEN;
            dM_QUY.SO_TIEN = sO_TIEN;
            dM_QUY.ID_DVT = iD_DVT;
            return dM_QUY;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_USER
        {
            get
            {
                return _ID_USER;
            }
            set
            {
                OnID_USERChanging(value);
                ReportPropertyChanging("ID_USER");
                _ID_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_USER");
                OnID_USERChanged();
            }
        }
        private global::System.Decimal _ID_USER;
        partial void OnID_USERChanging(global::System.Decimal value);
        partial void OnID_USERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TEN
        {
            get
            {
                return _TEN;
            }
            set
            {
                OnTENChanging(value);
                ReportPropertyChanging("TEN");
                _TEN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TEN");
                OnTENChanged();
            }
        }
        private global::System.String _TEN;
        partial void OnTENChanging(global::System.String value);
        partial void OnTENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SO_TIEN
        {
            get
            {
                return _SO_TIEN;
            }
            set
            {
                OnSO_TIENChanging(value);
                ReportPropertyChanging("SO_TIEN");
                _SO_TIEN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SO_TIEN");
                OnSO_TIENChanged();
            }
        }
        private global::System.Decimal _SO_TIEN;
        partial void OnSO_TIENChanging(global::System.Decimal value);
        partial void OnSO_TIENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_DVT
        {
            get
            {
                return _ID_DVT;
            }
            set
            {
                OnID_DVTChanging(value);
                ReportPropertyChanging("ID_DVT");
                _ID_DVT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_DVT");
                OnID_DVTChanged();
            }
        }
        private global::System.Decimal _ID_DVT;
        partial void OnID_DVTChanging(global::System.Decimal value);
        partial void OnID_DVTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LOG_SO_TIEN
        {
            get
            {
                return _LOG_SO_TIEN;
            }
            set
            {
                OnLOG_SO_TIENChanging(value);
                ReportPropertyChanging("LOG_SO_TIEN");
                _LOG_SO_TIEN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOG_SO_TIEN");
                OnLOG_SO_TIENChanged();
            }
        }
        private Nullable<global::System.Decimal> _LOG_SO_TIEN;
        partial void OnLOG_SO_TIENChanging(Nullable<global::System.Decimal> value);
        partial void OnLOG_SO_TIENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHI_CHU
        {
            get
            {
                return _GHI_CHU;
            }
            set
            {
                OnGHI_CHUChanging(value);
                ReportPropertyChanging("GHI_CHU");
                _GHI_CHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHI_CHU");
                OnGHI_CHUChanged();
            }
        }
        private global::System.String _GHI_CHU;
        partial void OnGHI_CHUChanging(global::System.String value);
        partial void OnGHI_CHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_DM_QUY_DM_DVT", "DM_DVT")]
        public DM_DVT DM_DVT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_DVT>("QLTC_MVCModel.FK_DM_QUY_DM_DVT", "DM_DVT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_DVT>("QLTC_MVCModel.FK_DM_QUY_DM_DVT", "DM_DVT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DM_DVT> DM_DVTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_DVT>("QLTC_MVCModel.FK_DM_QUY_DM_DVT", "DM_DVT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DM_DVT>("QLTC_MVCModel.FK_DM_QUY_DM_DVT", "DM_DVT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_DM_QUY_USER", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_DM_QUY_USER", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_DM_QUY_USER", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_DM_QUY_USER", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("QLTC_MVCModel.FK_DM_QUY_USER", "USER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_QUY", "GD_THU_CHI")]
        public EntityCollection<GD_THU_CHI> GD_THU_CHI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_QUY", "GD_THU_CHI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_QUY", "GD_THU_CHI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTC_MVCModel", Name="DM_THU_CHI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DM_THU_CHI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DM_THU_CHI object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tEN">Initial value of the TEN property.</param>
        /// <param name="iD_LOAI">Initial value of the ID_LOAI property.</param>
        /// <param name="iD_USER">Initial value of the ID_USER property.</param>
        public static DM_THU_CHI CreateDM_THU_CHI(global::System.Decimal id, global::System.String tEN, global::System.Decimal iD_LOAI, global::System.Decimal iD_USER)
        {
            DM_THU_CHI dM_THU_CHI = new DM_THU_CHI();
            dM_THU_CHI.ID = id;
            dM_THU_CHI.TEN = tEN;
            dM_THU_CHI.ID_LOAI = iD_LOAI;
            dM_THU_CHI.ID_USER = iD_USER;
            return dM_THU_CHI;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TEN
        {
            get
            {
                return _TEN;
            }
            set
            {
                OnTENChanging(value);
                ReportPropertyChanging("TEN");
                _TEN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TEN");
                OnTENChanged();
            }
        }
        private global::System.String _TEN;
        partial void OnTENChanging(global::System.String value);
        partial void OnTENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_LOAI
        {
            get
            {
                return _ID_LOAI;
            }
            set
            {
                OnID_LOAIChanging(value);
                ReportPropertyChanging("ID_LOAI");
                _ID_LOAI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_LOAI");
                OnID_LOAIChanged();
            }
        }
        private global::System.Decimal _ID_LOAI;
        partial void OnID_LOAIChanging(global::System.Decimal value);
        partial void OnID_LOAIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_USER
        {
            get
            {
                return _ID_USER;
            }
            set
            {
                OnID_USERChanging(value);
                ReportPropertyChanging("ID_USER");
                _ID_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_USER");
                OnID_USERChanged();
            }
        }
        private global::System.Decimal _ID_USER;
        partial void OnID_USERChanging(global::System.Decimal value);
        partial void OnID_USERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHI_CHU
        {
            get
            {
                return _GHI_CHU;
            }
            set
            {
                OnGHI_CHUChanging(value);
                ReportPropertyChanging("GHI_CHU");
                _GHI_CHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHI_CHU");
                OnGHI_CHUChanged();
            }
        }
        private global::System.String _GHI_CHU;
        partial void OnGHI_CHUChanging(global::System.String value);
        partial void OnGHI_CHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_DM_THU_CHI_DM_TU_DIEN", "DM_TU_DIEN")]
        public DM_TU_DIEN DM_TU_DIEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_TU_DIEN>("QLTC_MVCModel.FK_DM_THU_CHI_DM_TU_DIEN", "DM_TU_DIEN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_TU_DIEN>("QLTC_MVCModel.FK_DM_THU_CHI_DM_TU_DIEN", "DM_TU_DIEN").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DM_TU_DIEN> DM_TU_DIENReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_TU_DIEN>("QLTC_MVCModel.FK_DM_THU_CHI_DM_TU_DIEN", "DM_TU_DIEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DM_TU_DIEN>("QLTC_MVCModel.FK_DM_THU_CHI_DM_TU_DIEN", "DM_TU_DIEN", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_DM_THU_CHI_USER", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_DM_THU_CHI_USER", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_DM_THU_CHI_USER", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_DM_THU_CHI_USER", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("QLTC_MVCModel.FK_DM_THU_CHI_USER", "USER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_THU_CHI", "GD_THU_CHI")]
        public EntityCollection<GD_THU_CHI> GD_THU_CHI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_THU_CHI", "GD_THU_CHI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_THU_CHI", "GD_THU_CHI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTC_MVCModel", Name="DM_TU_DIEN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DM_TU_DIEN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DM_TU_DIEN object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tEN">Initial value of the TEN property.</param>
        /// <param name="tEM_NGAN">Initial value of the TEM_NGAN property.</param>
        public static DM_TU_DIEN CreateDM_TU_DIEN(global::System.Decimal id, global::System.String tEN, global::System.String tEM_NGAN)
        {
            DM_TU_DIEN dM_TU_DIEN = new DM_TU_DIEN();
            dM_TU_DIEN.ID = id;
            dM_TU_DIEN.TEN = tEN;
            dM_TU_DIEN.TEM_NGAN = tEM_NGAN;
            return dM_TU_DIEN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TEN
        {
            get
            {
                return _TEN;
            }
            set
            {
                OnTENChanging(value);
                ReportPropertyChanging("TEN");
                _TEN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TEN");
                OnTENChanged();
            }
        }
        private global::System.String _TEN;
        partial void OnTENChanging(global::System.String value);
        partial void OnTENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TEM_NGAN
        {
            get
            {
                return _TEM_NGAN;
            }
            set
            {
                OnTEM_NGANChanging(value);
                ReportPropertyChanging("TEM_NGAN");
                _TEM_NGAN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TEM_NGAN");
                OnTEM_NGANChanged();
            }
        }
        private global::System.String _TEM_NGAN;
        partial void OnTEM_NGANChanging(global::System.String value);
        partial void OnTEM_NGANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MO_TA
        {
            get
            {
                return _MO_TA;
            }
            set
            {
                OnMO_TAChanging(value);
                ReportPropertyChanging("MO_TA");
                _MO_TA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MO_TA");
                OnMO_TAChanged();
            }
        }
        private global::System.String _MO_TA;
        partial void OnMO_TAChanging(global::System.String value);
        partial void OnMO_TAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHI_CHU
        {
            get
            {
                return _GHI_CHU;
            }
            set
            {
                OnGHI_CHUChanging(value);
                ReportPropertyChanging("GHI_CHU");
                _GHI_CHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHI_CHU");
                OnGHI_CHUChanged();
            }
        }
        private global::System.String _GHI_CHU;
        partial void OnGHI_CHUChanging(global::System.String value);
        partial void OnGHI_CHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_DM_THU_CHI_DM_TU_DIEN", "DM_THU_CHI")]
        public EntityCollection<DM_THU_CHI> DM_THU_CHI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DM_THU_CHI>("QLTC_MVCModel.FK_DM_THU_CHI_DM_TU_DIEN", "DM_THU_CHI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DM_THU_CHI>("QLTC_MVCModel.FK_DM_THU_CHI_DM_TU_DIEN", "DM_THU_CHI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTC_MVCModel", Name="GD_THU_CHI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GD_THU_CHI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GD_THU_CHI object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tHOI_GIAN">Initial value of the THOI_GIAN property.</param>
        /// <param name="iD_THU_CHI">Initial value of the ID_THU_CHI property.</param>
        /// <param name="sO_TIEN">Initial value of the SO_TIEN property.</param>
        /// <param name="iD_DVT">Initial value of the ID_DVT property.</param>
        /// <param name="iD_QUY">Initial value of the ID_QUY property.</param>
        public static GD_THU_CHI CreateGD_THU_CHI(global::System.Decimal id, global::System.DateTime tHOI_GIAN, global::System.Decimal iD_THU_CHI, global::System.Decimal sO_TIEN, global::System.Decimal iD_DVT, global::System.Decimal iD_QUY)
        {
            GD_THU_CHI gD_THU_CHI = new GD_THU_CHI();
            gD_THU_CHI.ID = id;
            gD_THU_CHI.THOI_GIAN = tHOI_GIAN;
            gD_THU_CHI.ID_THU_CHI = iD_THU_CHI;
            gD_THU_CHI.SO_TIEN = sO_TIEN;
            gD_THU_CHI.ID_DVT = iD_DVT;
            gD_THU_CHI.ID_QUY = iD_QUY;
            return gD_THU_CHI;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime THOI_GIAN
        {
            get
            {
                return _THOI_GIAN;
            }
            set
            {
                OnTHOI_GIANChanging(value);
                ReportPropertyChanging("THOI_GIAN");
                _THOI_GIAN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("THOI_GIAN");
                OnTHOI_GIANChanged();
            }
        }
        private global::System.DateTime _THOI_GIAN;
        partial void OnTHOI_GIANChanging(global::System.DateTime value);
        partial void OnTHOI_GIANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_THU_CHI
        {
            get
            {
                return _ID_THU_CHI;
            }
            set
            {
                OnID_THU_CHIChanging(value);
                ReportPropertyChanging("ID_THU_CHI");
                _ID_THU_CHI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_THU_CHI");
                OnID_THU_CHIChanged();
            }
        }
        private global::System.Decimal _ID_THU_CHI;
        partial void OnID_THU_CHIChanging(global::System.Decimal value);
        partial void OnID_THU_CHIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SO_TIEN
        {
            get
            {
                return _SO_TIEN;
            }
            set
            {
                OnSO_TIENChanging(value);
                ReportPropertyChanging("SO_TIEN");
                _SO_TIEN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SO_TIEN");
                OnSO_TIENChanged();
            }
        }
        private global::System.Decimal _SO_TIEN;
        partial void OnSO_TIENChanging(global::System.Decimal value);
        partial void OnSO_TIENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_DVT
        {
            get
            {
                return _ID_DVT;
            }
            set
            {
                OnID_DVTChanging(value);
                ReportPropertyChanging("ID_DVT");
                _ID_DVT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_DVT");
                OnID_DVTChanged();
            }
        }
        private global::System.Decimal _ID_DVT;
        partial void OnID_DVTChanging(global::System.Decimal value);
        partial void OnID_DVTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_QUY
        {
            get
            {
                return _ID_QUY;
            }
            set
            {
                OnID_QUYChanging(value);
                ReportPropertyChanging("ID_QUY");
                _ID_QUY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_QUY");
                OnID_QUYChanged();
            }
        }
        private global::System.Decimal _ID_QUY;
        partial void OnID_QUYChanging(global::System.Decimal value);
        partial void OnID_QUYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHI_CHU
        {
            get
            {
                return _GHI_CHU;
            }
            set
            {
                OnGHI_CHUChanging(value);
                ReportPropertyChanging("GHI_CHU");
                _GHI_CHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHI_CHU");
                OnGHI_CHUChanged();
            }
        }
        private global::System.String _GHI_CHU;
        partial void OnGHI_CHUChanging(global::System.String value);
        partial void OnGHI_CHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_DVT", "DM_DVT")]
        public DM_DVT DM_DVT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_DVT>("QLTC_MVCModel.FK_GD_THU_CHI_DM_DVT", "DM_DVT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_DVT>("QLTC_MVCModel.FK_GD_THU_CHI_DM_DVT", "DM_DVT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DM_DVT> DM_DVTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_DVT>("QLTC_MVCModel.FK_GD_THU_CHI_DM_DVT", "DM_DVT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DM_DVT>("QLTC_MVCModel.FK_GD_THU_CHI_DM_DVT", "DM_DVT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_QUY", "DM_QUY")]
        public DM_QUY DM_QUY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_QUY>("QLTC_MVCModel.FK_GD_THU_CHI_DM_QUY", "DM_QUY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_QUY>("QLTC_MVCModel.FK_GD_THU_CHI_DM_QUY", "DM_QUY").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DM_QUY> DM_QUYReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_QUY>("QLTC_MVCModel.FK_GD_THU_CHI_DM_QUY", "DM_QUY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DM_QUY>("QLTC_MVCModel.FK_GD_THU_CHI_DM_QUY", "DM_QUY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_GD_THU_CHI_DM_THU_CHI", "DM_THU_CHI")]
        public DM_THU_CHI DM_THU_CHI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_THU_CHI", "DM_THU_CHI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_THU_CHI", "DM_THU_CHI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DM_THU_CHI> DM_THU_CHIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DM_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_THU_CHI", "DM_THU_CHI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DM_THU_CHI>("QLTC_MVCModel.FK_GD_THU_CHI_DM_THU_CHI", "DM_THU_CHI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTC_MVCModel", Name="LOG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LOG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LOG object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iD_USER">Initial value of the ID_USER property.</param>
        /// <param name="tIME">Initial value of the TIME property.</param>
        /// <param name="aCTION">Initial value of the ACTION property.</param>
        public static LOG CreateLOG(global::System.Decimal id, global::System.Decimal iD_USER, global::System.DateTime tIME, global::System.String aCTION)
        {
            LOG lOG = new LOG();
            lOG.ID = id;
            lOG.ID_USER = iD_USER;
            lOG.TIME = tIME;
            lOG.ACTION = aCTION;
            return lOG;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_USER
        {
            get
            {
                return _ID_USER;
            }
            set
            {
                OnID_USERChanging(value);
                ReportPropertyChanging("ID_USER");
                _ID_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_USER");
                OnID_USERChanged();
            }
        }
        private global::System.Decimal _ID_USER;
        partial void OnID_USERChanging(global::System.Decimal value);
        partial void OnID_USERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TIME
        {
            get
            {
                return _TIME;
            }
            set
            {
                OnTIMEChanging(value);
                ReportPropertyChanging("TIME");
                _TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIME");
                OnTIMEChanged();
            }
        }
        private global::System.DateTime _TIME;
        partial void OnTIMEChanging(global::System.DateTime value);
        partial void OnTIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ACTION
        {
            get
            {
                return _ACTION;
            }
            set
            {
                OnACTIONChanging(value);
                ReportPropertyChanging("ACTION");
                _ACTION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ACTION");
                OnACTIONChanged();
            }
        }
        private global::System.String _ACTION;
        partial void OnACTIONChanging(global::System.String value);
        partial void OnACTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHI_CHU
        {
            get
            {
                return _GHI_CHU;
            }
            set
            {
                OnGHI_CHUChanging(value);
                ReportPropertyChanging("GHI_CHU");
                _GHI_CHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHI_CHU");
                OnGHI_CHUChanged();
            }
        }
        private global::System.String _GHI_CHU;
        partial void OnGHI_CHUChanging(global::System.String value);
        partial void OnGHI_CHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_LOG_USER", "USER")]
        public USER USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_LOG_USER", "USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_LOG_USER", "USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USER> USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USER>("QLTC_MVCModel.FK_LOG_USER", "USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USER>("QLTC_MVCModel.FK_LOG_USER", "USER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTC_MVCModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QLTC_MVCModel", Name="USER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="uSER_NAME">Initial value of the USER_NAME property.</param>
        public static USER CreateUSER(global::System.Decimal id, global::System.String uSER_NAME)
        {
            USER uSER = new USER();
            uSER.ID = id;
            uSER.USER_NAME = uSER_NAME;
            return uSER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USER_NAME
        {
            get
            {
                return _USER_NAME;
            }
            set
            {
                OnUSER_NAMEChanging(value);
                ReportPropertyChanging("USER_NAME");
                _USER_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USER_NAME");
                OnUSER_NAMEChanged();
            }
        }
        private global::System.String _USER_NAME;
        partial void OnUSER_NAMEChanging(global::System.String value);
        partial void OnUSER_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACCOUNT_NAME
        {
            get
            {
                return _ACCOUNT_NAME;
            }
            set
            {
                OnACCOUNT_NAMEChanging(value);
                ReportPropertyChanging("ACCOUNT_NAME");
                _ACCOUNT_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACCOUNT_NAME");
                OnACCOUNT_NAMEChanged();
            }
        }
        private global::System.String _ACCOUNT_NAME;
        partial void OnACCOUNT_NAMEChanging(global::System.String value);
        partial void OnACCOUNT_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FACEBOOK
        {
            get
            {
                return _FACEBOOK;
            }
            set
            {
                OnFACEBOOKChanging(value);
                ReportPropertyChanging("FACEBOOK");
                _FACEBOOK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FACEBOOK");
                OnFACEBOOKChanged();
            }
        }
        private global::System.String _FACEBOOK;
        partial void OnFACEBOOKChanging(global::System.String value);
        partial void OnFACEBOOKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GHI_CHU
        {
            get
            {
                return _GHI_CHU;
            }
            set
            {
                OnGHI_CHUChanging(value);
                ReportPropertyChanging("GHI_CHU");
                _GHI_CHU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GHI_CHU");
                OnGHI_CHUChanged();
            }
        }
        private global::System.String _GHI_CHU;
        partial void OnGHI_CHUChanging(global::System.String value);
        partial void OnGHI_CHUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_DM_QUY_USER", "DM_QUY")]
        public EntityCollection<DM_QUY> DM_QUY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DM_QUY>("QLTC_MVCModel.FK_DM_QUY_USER", "DM_QUY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DM_QUY>("QLTC_MVCModel.FK_DM_QUY_USER", "DM_QUY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_DM_THU_CHI_USER", "DM_THU_CHI")]
        public EntityCollection<DM_THU_CHI> DM_THU_CHI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DM_THU_CHI>("QLTC_MVCModel.FK_DM_THU_CHI_USER", "DM_THU_CHI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DM_THU_CHI>("QLTC_MVCModel.FK_DM_THU_CHI_USER", "DM_THU_CHI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QLTC_MVCModel", "FK_LOG_USER", "LOG")]
        public EntityCollection<LOG> LOGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LOG>("QLTC_MVCModel.FK_LOG_USER", "LOG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LOG>("QLTC_MVCModel.FK_LOG_USER", "LOG", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
