//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQLTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DVT
    {
        public DM_DVT()
        {
            this.DM_QUY = new HashSet<DM_QUY>();
            this.GD_THU_CHI = new HashSet<GD_THU_CHI>();
        }
    
        public decimal ID { get; set; }
        public string TEN { get; set; }
        public string KI_HIEU { get; set; }
        public decimal QUY_DOI_USD { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual ICollection<DM_QUY> DM_QUY { get; set; }
        public virtual ICollection<GD_THU_CHI> GD_THU_CHI { get; set; }
    }
}
