//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQLTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TU_DIEN
    {
        public DM_TU_DIEN()
        {
            this.DM_THU_CHI = new HashSet<DM_THU_CHI>();
        }
    
        public decimal ID { get; set; }
        public string TEN { get; set; }
        public string TEM_NGAN { get; set; }
        public string MO_TA { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual ICollection<DM_THU_CHI> DM_THU_CHI { get; set; }
    }
}
